### ISSUE TITLE
esp32 IntegerDivideByZero

### ISSUE THREAD

**Issue by DeverosTV** [hpwit/artnet#1]
greetings.

i dont know what i am doing wrong here.

i am using the ArtnetNeoPixelESPSync example.
doing the minimum changes (ssid, password, number of leds)
i compile it with arduino ide 1.8.8 and it is ok
i upload it to a esp devkit v1 doit.

and when i see the serial port i get this error

`Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:10088
load:0x40080400,len:6380
entry 0x400806a4
.....
Connected to chavin
IP address: 192.168.1.4
Guru Meditation Error: Core  1 panic'ed (IntegerDivideByZero). Exception was unhandled.
Core 1 register dump:
PC      : 0x400d1b7b  PS      : 0x00060230  A0      : 0x800d1809  A1      : 0x3ffb1f50  
A2      : 0x00000001  A3      : 0x3ffc0dc4  A4      : 0x00000000  A5      : 0x00000000  
A6      : 0x3ffc0ac4  A7      : 0x00000b49  A8      : 0x800d1a2b  A9      : 0x00000000  
A10     : 0x00000b49  A11     : 0x3ffc0ae8  A12     : 0x3ffb7f87  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0xff000000  SAR     : 0x0000000a  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  

Backtrace: 0x400d1b7b:0x3ffb1f50 0x400d1806:0x3ffb1f90 0x400d3955:0x3ffb1fb0 0x4008e765:0x3ffb1fd0`

i know i am doing something wrong, when i try the adafruit version (with fastled library) i can not get resolume to find the esp32.

i hope you can help me with this issue.

**Comment by hpwit** [comment]
You need to run this example. https://github.com/hpwit/artnet/tree/master/examples/exampleArtnet
Let me know 
Rgds
Yves

**Comment by yusufsulaiman** [comment]
hi, i have try run this example. https://github.com/hpwit/artnet/tree/master/examples/exampleArtnet, and  i have get error 
In file included from C:\Users\lenovo\Documents\Arduino\libraries\artnet-master/Artnet.h:29:0,

                 from sketch\Artnet.cpp:25:

C:\Users\lenovo\Documents\Arduino\libraries\FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.006

 #    pragma message "FastLED version 3.002.006"

                     ^

In file included from C:\Users\lenovo\Documents\Arduino\libraries\FastLED/FastLED.h:65:0,

                 from C:\Users\lenovo\Documents\Arduino\libraries\artnet-master/Artnet.h:29,

                 from sketch\Artnet.cpp:25:

C:\Users\lenovo\Documents\Arduino\libraries\FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

In file included from C:\Users\lenovo\Documents\Arduino\libraries\artnet-master/Artnet.h:29:0,

                 from C:\Users\lenovo\Documents\Arduino\exampleArtnet\exampleArtnet.ino:5:

C:\Users\lenovo\Documents\Arduino\libraries\FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.006

 #    pragma message "FastLED version 3.002.006"

                     ^

In file included from C:\Users\lenovo\Documents\Arduino\libraries\FastLED/FastLED.h:65:0,

                 from C:\Users\lenovo\Documents\Arduino\libraries\artnet-master/Artnet.h:29,

                 from C:\Users\lenovo\Documents\Arduino\exampleArtnet\exampleArtnet.ino:5:

C:\Users\lenovo\Documents\Arduino\libraries\FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

In file included from C:\Users\lenovo\Documents\Arduino\libraries\FastLED/FastLED.h:48:0,

                 from C:\Users\lenovo\Documents\Arduino\libraries\artnet-master/Artnet.h:29,

                 from C:\Users\lenovo\Documents\Arduino\exampleArtnet\exampleArtnet.ino:5:

C:\Users\lenovo\Documents\Arduino\libraries\FastLED/fastpin.h: In instantiation of 'class FastPin<6u>':

C:\Users\lenovo\Documents\Arduino\libraries\FastLED/platforms/esp/32/clockless_esp32.h:182:23:   required from 'class ClocklessController<6, 60, 150, 90, (EOrder)66u, 0, false, 5>'

C:\Users\lenovo\Documents\Arduino\libraries\FastLED/chipsets.h:550:7:   required from 'class WS2812Controller800Khz<6u, (EOrder)66u>'

C:\Users\lenovo\Documents\Arduino\libraries\FastLED/FastLED.h:92:34:   required from 'class NEOPIXEL<6u>'

C:\Users\lenovo\Documents\Arduino\libraries\FastLED/FastLED.h:314:28:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = NEOPIXEL; unsigned char DATA_PIN = 6u]'

C:\Users\lenovo\Documents\Arduino\exampleArtnet\exampleArtnet.ino:90:46:   required from here

C:\Users\lenovo\Documents\Arduino\libraries\FastLED/fastpin.h:207:2: error: static assertion failed: Invalid pin specified

  static_assert(validpin(), "Invalid pin specified");

  ^
i hope you can help me with this issue.. thanks

**Comment by djravi** [comment]
error: I2S.h: No such file or directory
I have this error anyone helps me where I found I2S.h library

**Comment by hpwit** [comment]
I will need to change the code now the new driver has been integrated with Fastled

**Comment by djravi** [comment]
> I will need to change the code now the new driver has been integrated with Fastled

When you change the code

**Comment by djravi** [comment]
please upload new updated code

**Comment by DeverosTV** [comment]
i apologize for my late reply.

i just got time to test the "example" ino.
i cant get it compile.
the MUST READ file says i only need the standard ethernet library, i assume it means the one that comes with arduino ide? if so i have it, also i know i need fastled, which i have it.

can you tell me what am i missing?

error is "i2s.h  no such  file or directory", when i search for that one explicitly in the library manager i can see 2 libraries, a experimental one and one from adafruit.

**Comment by DeverosTV** [comment]
hello again.

i download the i2s library from your repertory, now i do not have that issue but i have a new one...


first_test:69:31: error: 'class Artnet' has no member named 'getframe'

            memcpy(leds,artnet.getframe(),NUM_LEDS*sizeof(CRGB));

                               ^

C:\Users\Deveros\Desktop\esp32\nuevo esp32 arduino\1ra prueba\first_test\first_test.ino: In function 'void setup()':

first_test:102:38: error: no matching function for call to 'Artnet::begin(int, int, int)'

 artnet.begin(NUM_LEDS,UNIVERSE_SIZE,1); //the number of pixels and the maximum size of your iniverses 1 represent the buffer

                                      ^

In file included from C:\Users\Deveros\Desktop\esp32\nuevo esp32 arduino\1ra prueba\first_test\first_test.ino:8:0:

C:\Users\Deveros\Documents\Arduino\libraries\Artnet-master/Artnet.h:100:8: note: candidate: void Artnet::begin(byte*, byte*)

   void begin(byte mac[], byte ip[]);

        ^

C:\Users\Deveros\Documents\Arduino\libraries\Artnet-master/Artnet.h:100:8: note:   candidate expects 2 arguments, 3 provided

C:\Users\Deveros\Documents\Arduino\libraries\Artnet-master/Artnet.h:101:8: note: candidate: void Artnet::begin()

   void begin();

        ^

C:\Users\Deveros\Documents\Arduino\libraries\Artnet-master/Artnet.h:101:8: note:   candidate expects 0 arguments, 3 provided

C:\Users\Deveros\Desktop\esp32\nuevo esp32 arduino\1ra prueba\first_test\first_test.ino: In function 'void loop()':

first_test:112:10: error: 'class Artnet' has no member named 'resetsync'

   artnet.resetsync();

          ^

Se encontraron varias bibliotecas para "WiFi.h"
Usado: C:\Users\Deveros\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.2\libraries\WiFi
 No usado: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
'class Artnet' has no member named 'getframe'

**Comment by DeverosTV** [comment]
fast update.
your i2s library must be downloaded for the example file.

i changed getframe to getDMXFrame.

right now i got this 2 issues

no matching function for call to 'artnet::begin(int, int, int)'

first_test:113:10: error: 'class Artnet' has no member named 'resetsync'
   artnet.resetsync();


i tried to change artnet.begin to Artnet.begin (according to your keyword txt) but it didnt help

**Comment by hpwit** [comment]
Hello
which script are u executing ?

**Comment by hpwit** [comment]
hello can you re upload ?
i have made small changes and it's compiling on my laptop
but i never got the same error as you .
let me know

**Comment by DeverosTV** [comment]
just saw your changes.

i2s.h error i fix it by downloading your newi2s library.

the new example, i just download it, same errors.

`In file included from C:\Users\Deveros\Desktop\esp32\nuevo esp32 arduino\1ra prueba\3rd test\3rdtest\3rdtest.ino:7:0:

C:\Users\Deveros\Documents\Arduino\libraries\fastledyves-master/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.006

 #    pragma message "FastLED version 3.002.006"

                     ^

In file included from C:\Users\Deveros\Documents\Arduino\libraries\fastledyves-master/FastLED.h:65:0,

                 from C:\Users\Deveros\Desktop\esp32\nuevo esp32 arduino\1ra prueba\3rd test\3rdtest\3rdtest.ino:7:

C:\Users\Deveros\Documents\Arduino\libraries\fastledyves-master/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

C:\Users\Deveros\Desktop\esp32\nuevo esp32 arduino\1ra prueba\3rd test\3rdtest\3rdtest.ino: In function 'void FastLEDshowTask2(void*)':

3rdtest:65:31: error: 'class Artnet' has no member named 'getframe'

            memcpy(leds,artnet.getframe(),NUM_LEDS*sizeof(CRGB));

                               ^

C:\Users\Deveros\Desktop\esp32\nuevo esp32 arduino\1ra prueba\3rd test\3rdtest\3rdtest.ino: In function 'void setup()':

3rdtest:98:38: error: no matching function for call to 'Artnet::begin(int, int, int)'

 artnet.begin(NUM_LEDS,UNIVERSE_SIZE,1); //the number of pixels and the maximum size of your iniverses 1 represent the buffer

                                      ^

In file included from C:\Users\Deveros\Desktop\esp32\nuevo esp32 arduino\1ra prueba\3rd test\3rdtest\3rdtest.ino:5:0:

C:\Users\Deveros\Documents\Arduino\libraries\Artnet-master/Artnet.h:100:8: note: candidate: void Artnet::begin(byte*, byte*)

   void begin(byte mac[], byte ip[]);

        ^

C:\Users\Deveros\Documents\Arduino\libraries\Artnet-master/Artnet.h:100:8: note:   candidate expects 2 arguments, 3 provided

C:\Users\Deveros\Documents\Arduino\libraries\Artnet-master/Artnet.h:101:8: note: candidate: void Artnet::begin()

   void begin();

        ^

C:\Users\Deveros\Documents\Arduino\libraries\Artnet-master/Artnet.h:101:8: note:   candidate expects 0 arguments, 3 provided

C:\Users\Deveros\Desktop\esp32\nuevo esp32 arduino\1ra prueba\3rd test\3rdtest\3rdtest.ino: In function 'void loop()':

3rdtest:108:10: error: 'class Artnet' has no member named 'resetsync'

   artnet.resetsync();

          ^

Se encontraron varias bibliotecas para "WiFi.h"
Usado: C:\Users\Deveros\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.2\libraries\WiFi
 No usado: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
'class Artnet' has no member named 'getframe'`

**Comment by DeverosTV** [comment]
i am deeply sorry.
i swap libraries or so it seems, now it compiles directly (with and without the changes you just did)

i am so sorry for the inconvenience.

in a couple of days i will try it in a  15 * 36 array with resolume/jynx wish me luck.

**Comment by hpwit** [comment]
No problem at all ;)
If you need help let me know.
