### ISSUE TITLE
Compilation error: 'class WiFiUDP' has no member named 'udpBuffer'

### ISSUE THREAD

**Issue by maramb81** [hpwit/artnet#2]
Hi 

Thank you for sharing your great work.
I'm using:
Arduino 1.8.12
ESP32 1.0.4
your last https://github.com/hpwit/fastled-esp32-16PINS
your last https://github.com/hpwit/artnet

i'm using this skatch
https://github.com/hpwit/artnet/blob/master/examples/exampleArtnet/exampleArtnet.ino

but change some code

(-)  FastLED.addLeds<WS2812B, 12>(leds, NUM_LEDS);

(+)   FastLED.addLeds<WS2812B, PIN1, GRB>(leds, 0*PIXEL_PER_PIN, PIXEL_PER_PIN); 
(+)   FastLED.addLeds<WS2812B, PIN2, GRB>(leds, 1*PIXEL_PER_PIN, PIXEL_PER_PIN); 
(+)   FastLED.addLeds<WS2812B, PIN3, GRB>(leds, 2*PIXEL_PER_PIN, PIXEL_PER_PIN); 
(+)   FastLED.addLeds<WS2812B, PIN4, GRB>(leds, 3*PIXEL_PER_PIN, PIXEL_PER_PIN); 
(+)   FastLED.addLeds<WS2812B, PIN5, GRB>(leds, 4*PIXEL_PER_PIN, PIXEL_PER_PIN); 

`
C:\Users\amb\Documents\Arduino\libraries\artnet-master\Artnet.cpp: In member function 'uint16_t Artnet::read()':

C:\Users\amb\Documents\Arduino\libraries\artnet-master\Artnet.cpp:160:20: error: 'class WiFiUDP' has no member named 'parsePacket2'

   packetSize = Udp.parsePacket2();

                    ^

C:\Users\amb\Documents\Arduino\libraries\artnet-master\Artnet.cpp:176:20: error: 'class WiFiUDP' has no member named 'udpBuffer'

       opcode = Udp.udpBuffer[8] | (Udp.udpBuffer[9] << 8);//artnetPacket[8] | artnetPacket[9] << 8;

                    ^

C:\Users\amb\Documents\Arduino\libraries\artnet-master\Artnet.cpp:176:40: error: 'class WiFiUDP' has no member named 'udpBuffer'

       opcode = Udp.udpBuffer[8] | (Udp.udpBuffer[9] << 8);//artnetPacket[8] | artnetPacket[9] << 8;

                                        ^

C:\Users\amb\Documents\Arduino\libraries\artnet-master\Artnet.cpp:183:32: error: 'class WiFiUDP' has no member named 'udpBuffer'

         incomingUniverse = Udp.udpBuffer[14] | (Udp.udpBuffer[15] << 8);//artnetPacket[14] | (artnetPacket[15] << 8);

                                ^

C:\Users\amb\Documents\Arduino\libraries\artnet-master\Artnet.cpp:183:53: error: 'class WiFiUDP' has no member named 'udpBuffer'

         incomingUniverse = Udp.udpBuffer[14] | (Udp.udpBuffer[15] << 8);//artnetPacket[14] | (artnetPacket[15] << 8);

                                                     ^

C:\Users\amb\Documents\Arduino\libraries\artnet-master\Artnet.cpp:184:29: error: 'class WiFiUDP' has no member named 'udpBuffer'

         dmxDataLength = Udp.udpBuffer[17] | Udp.udpBuffer[16] << 8; //artnetPacket[17] | artnetPacket[16] << 8;

                             ^

C:\Users\amb\Documents\Arduino\libraries\artnet-master\Artnet.cpp:184:49: error: 'class WiFiUDP' has no member named 'udpBuffer'

         dmxDataLength = Udp.udpBuffer[17] | Udp.udpBuffer[16] << 8; //artnetPacket[17] | artnetPacket[16] << 8;

                                                 ^

C:\Users\amb\Documents\Arduino\libraries\artnet-master\Artnet.cpp:195:82: error: 'class WiFiUDP' has no member named 'udpBuffer'

                memcpy(&artnetleds1[nbPixelsPerUniverse*(incomingUniverse)*3],Udp.udpBuffer + ART_DMX_START,dmxDataLength);

                                                                                  ^

Multiple libraries were found for "WiFi.h"
 Used: C:\Users\amb\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
 Not used: C:\Users\amb\Downloads\arduino-1.8.12-windows\arduino-1.8.12\libraries\WiFi

`

Regards

**Comment by hpwit** [comment]
hello
Indeed to make it work you need to replace the bases WifiUDP.h and WifiUDP.cpp
with a specific version i have made

**Comment by hpwit** [comment]
you should use the latest version of fastled
https://github.com/FastLED/FastLED
 my new version of this driver is integrated
just put
#define FASTLED_ESP32_I2S true
#include "FastLED.h"
and declare your strips normally

**Comment by maramb81** [comment]
Thank you so much

can i ask with this code, how many universe can i use on my ESP32 ?
now i can not use more then 9 universes.
i'm try to replicate this one
https://www.youtube.com/watch?v=IBal4XYcWVM
but with one ESP32 and 10 matrix 16x16  does't work.

later i'll try your code

Regards

**Comment by hpwit** [comment]
I have 35 universes to control 5904 leds
So to control 2560 leds it will be ok. 
I have just help someone implementing it with 11 universes. 
Per universe you can control 170 pixels maximum

**Comment by hpwit** [comment]
How many pins are you using ?

**Comment by maramb81** [comment]
hi

thank you, now it works fine.
actually i'm using 15 universe with 9 matrix 16x16 LED
i'm using just 3 pin each pin drive 768 LED

you solved my issue.
have a good days

**Comment by hpwit** [comment]
You’re welcome !!
